import { SuperCategory } from 'generated/prisma';

export const CATEGORY_TAGS: Record<SuperCategory, string[]> = {
  KNOWLEDGE_LEARNING: [
    'online-courses',
    'language-learning',
    'academic-subjects',
    'educational-research',
    'study-techniques',
    'professional-certification',
    'scientific-education',
    'historical-education',
    'skill-development',
    'educational-technology',
  ],

  BUSINESS_FINANCE: [
    'stock-market-analysis',
    'venture-capital',
    'personal-finance-management',
    'cryptocurrency-investment',
    'business-strategy',
    'financial-literacy',
    'tax-planning',
    'retirement-planning',
    'market-research',
    'business-leadership',
  ],

  COMPUTER_SCIENCE_TECH: [
    'frontend-development',
    'backend-systems',
    'machine-learning-applications',
    'cloud-architecture',
    'mobile-app-development',
    'database-management',
    'dev-ops-practices',
    'enterprise-software',
    'blockchain-technology',
    'embedded-systems',
  ],

  ARTS_CREATIVITY: [
    'oil-painting-techniques',
    'digital-illustration',
    'character-design',
    'sculptural-arts',
    'concept-art-creation',
    'visual-storytelling',
    'fine-art-practice',
    'mixed-media-techniques',
    'printmaking-methods',
    'pottery-ceramics',
  ],

  ENTERTAINMENT_MEDIA: [
    'film-critique',
    'television-analysis',
    'streaming-content-reviews',
    'entertainment-industry-insights',
    'celebrity-interviews',
    'film-production',
    'media-trend-analysis',
    'award-show-coverage',
    'behind-the-scenes-content',
    'nostalgia-retrospectives',
  ],

  GAMING_INTERACTIVE: [
    'competitive-esports',
    'game-development-insights',
    'speedrunning-techniques',
    'gaming-hardware-reviews',
    'retro-gaming-appreciation',
    'gameplay-strategy-guides',
    'multiplayer-community',
    'game-industry-analysis',
    'indie-game-spotlight',
    'virtual-reality-gaming',
  ],

  MUSIC_AUDIO: [
    'music-composition-technique',
    'audio-production-tutorials',
    'instrument-performance',
    'music-theory-education',
    'music-industry-business',
    'artist-interviews-features',
    'genre-specific-analysis',
    'recording-studio-techniques',
    'live-performance-insights',
    'music-equipment-reviews',
  ],

  HEALTH_WELLNESS: [
    'strength-training-programs',
    'nutritional-science',
    'mindfulness-practices',
    'sleep-optimization',
    'mental-health-strategies',
    'holistic-wellness',
    'stress-management-techniques',
    'preventative-healthcare',
    'specialized-diets',
    'chronic-condition-management',
  ],

  LIFESTYLE_PERSONAL: [
    'sustainable-living-practices',
    'minimalist-lifestyle',
    'home-renovation-design',
    'culinary-techniques',
    'travel-destination-guides',
    'fashion-trend-analysis',
    'relationship-psychology',
    'productivity-systems',
    'luxury-lifestyle',
    'family-parenting',
  ],

  SOCIETY_CULTURE: [
    'political-analysis',
    'social-justice-issues',
    'anthropological-studies',
    'cultural-heritage-preservation',
    'philosophical-discourse',
    'religious-studies',
    'current-events-commentary',
    'ethical-discussions',
    'sociological-perspectives',
    'historical-contexts',
  ],

  REVIEWS_PRODUCTS: [
    'consumer-electronics-evaluation',
    'smartphone-detailed-reviews',
    'automotive-testing',
    'home-appliance-comparisons',
    'tech-ecosystem-analysis',
    'camera-equipment-testing',
    'software-application-reviews',
    'gaming-gear-assessment',
    'wearable-technology-critique',
    'high-end-audio-evaluation',
  ],
};
